### ISSUE TITLE
Question about IndexError

### ISSUE THREAD

**Issue by DavidMStraub** [aas-core-works/abnf-to-regexp#26]
Hi, thanks for this library, it looks really cool. I have a question on an error I am encountering, apologies in advance that this is likely not an issue with your library, but perhaps you can lead me on the right track.

I was trying out `abnf-to-regexp` on the ABNF of the GEDCOM 7 standard:
https://github.com/FamilySearch/GEDCOM/releases/download/v7.0.10/grammar.abnf

There are two issues with this, one is `quoted-string` is not defined in the file (I guess that's an inconsistency there), the second is that I always get the error (thrown by `abnf`)
```
  File "~/.local/lib/python3.10/site-packages/abnf/parser.py", line 1126, in visit_concatenation
    return Concatenation(*args) if len(args) > 1 else args[0]
IndexError: list index out of range
```

I found through experimentation that this error goes away if I replace all occurrences of `""` with something else (e.g. `" "`).

Using `abnf_to_regexp` 1.1.1 with `abnf` 2.0.0 on Python 3.10.6.

**Comment by DavidMStraub** [comment]
(Just found that the `quoted-string` is indeed an error in that file: https://github.com/FamilySearch/GEDCOM/commit/9a388e9c562ce025d5592573842b48daf788f615.)

**Comment by mristin** [comment]
@DavidMStraub thanks for reporting! I'll try to make the error message a bit more informative, so that the user at least sees it was a parsing issue.

**Comment by mristin** [comment]
@DavidMStraub I re-visited the code. There is actually a check for errors in the grammar:

https://github.com/aas-core-works/abnf-to-regexp/blob/main/abnf_to_regexp/main.py#L95

So this seems to me like a potential undefined behavior in the underlying [abnf] module. I'll try to update to version 2.0.0 of [abnf], and then come back to you.

[abnf]: https://github.com/declaresub/abnf

**Comment by mristin** [comment]
@DavidMStraub The issue has been fixed upstream in https://github.com/declaresub/abnf/commit/d40d9659b067191d5d29117b24e1dc218645a087.

You merely have to update the dependency:

```
pip install --upgrade abnf
```

... and your example should work now with abnf 2.0.1.
